### ISSUE TITLE
Allow setup and teardown to return Result

### ISSUE THREAD

**Issue by taladar** [JasterV/test-context#21]
When doing non-trivial work in setup or teardown, e.g. opening a DB connection, clearing out the database and adding some test data, it would be useful to be able to use ? in the setup function.

**Comment by JasterV** [comment]
I'd say if something fails during Setup/Teardown you could just let if explode by using `unwrap` or `expect`
What was the specific use case of yours?

**Comment by taladar** [comment]
Using unwrap or expect is a bit annoying if you reuse the production code for part of the setup. It also conflicts with the lints that forbid their use.

I don't remember what I was working on exactly in May 2023 when I wrote the ticket.

**Comment by JasterV** [comment]
I see :D I think it should be fairly simple to allow the use of a Result, let's keep this open for now I guess

**Comment by JasterV** [comment]
For now I am closing this as not planned, but if in the future it is still relevant we can reopen it 👍🏻
