### ISSUE TITLE
Add test result params to teardown

### ISSUE THREAD

**Issue by jvliwanag** [JasterV/test-context#24]
Would it be possible to add test info onto the teardown? In particular, it would be useful to add context logs and skip some teardown to allow for investigation post test failures.

**Comment by JasterV** [comment]
Hello there! I'm the new maintainer of this crate :) 

I would like if you could give me a bit more details.

Could you explain your use case and how would you like as a user of the crate to use this features on your code? (For example, a code example of how would you like to do the teardown skip)

**Comment by JasterV** [comment]
@jvliwanag A new keyword has been introduced to allow you skip the teardown 😄 
Regarding logs, you should be able to add them yourselve inside the setup function and along your tests.

This library only adds a very thin wrapper around your test that executes the setup, passes the result into your test function and once your test is done it will call the teardown. 

So if you need any logging capabilities I would suggest to add them yourself as you please.

I will close this issue 👍🏻
