### ISSUE TITLE
Not sure how to use Context types with generic parameters

### ISSUE THREAD

**Issue by antifuchs** [JasterV/test-context#42]
I've defined a test context that takes a type parameter (it sets up a test DB, and the parameter specifying the behavior a user may want for how migrations should be handled); unfortunately, I can't figure out a way to specify that context in the attr macro invocation. I suspect the token parser just doesn't expect there to be a type parameter in the way.

The full code I'm writing is [here](https://github.com/antifuchs/lz/pull/9/files#diff-84aeb3a241eeb616d51ca92432af398e35af6c86608315e3984bc810f741bdc7R23) - I've worked around by defining a type `NonMigratingContext` that is `Context<NoMigrationBehavior>`. Here's a more boiled-down example:

```rust
use test_context::AsyncTestContext;
trait Behavior{
    fn do_thing() {println!("Default behavior!");}
}
struct Context<M: Behavior = DoThing1>();
impl<M: Behavior> AsyncTestContext for Context<M> {
    async fn setup() -> Context<M> {
        M::do_thing();
        Self()
    }
}

struct DoThing1();
impl Behavior for DoThing1{}
struct DoThingAbnormally();
impl Behavior for DoThingAbnormally{
    fn do_thing() { println!("abnormal behavior!"); }
}
```

With the above, the following fails:

```rust
#[test_context(Context<DoThingAbnormally>)]
#[tokio::test]
async fn test_foo(ctx: Context<DoThingAbnormally>) {
    assert_eq!(1, 1);
}
```

**Comment by JasterV** [comment]
Hi @antifuchs ! Sorry for the late reply, I don't know why I didn't get notified

Well so as you suspect, Generics are not supported on the macro at the moment.

I have to say tho that for tests I usually create 1 Context type per use case.

So lets say you have tests that use 2 behavior implementations, you would then have 2 Context types.

I would suggest that as a Workaround:) 

I will investigate and see if I can make it support generics on the future though!

**Comment by JasterV** [comment]
In any case, this library tries to be very simplistic and introducing generics could add a lot of complexity
Specially because I could see how people then would ask for a dependency injection feature (Injecting dependencies on the setup function) and I don't really plan on adding stuff like that on this library.

If you need to inject generics maybe you want to try out this library: https://github.com/la10736/rstest

**Comment by JasterV** [comment]
Another suggestion would be to try this:

```rust
impl<M: Behavior> AsyncTestContext for M {
    async fn setup() -> M {
        Self::do_thing();
        Self()
    }
}
```
